spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/boydos/SpringCloudConfig/
          search-paths: config
          username:
          password:
server:
  port: 8789
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

